#!/usr/bin/env bash

readonly env_name="$1"
readonly repo_name=gardens

# source the config
readonly config_file="$HOME/.gardens/$env_name.conf"
source $config_file
export $(cut -d= -f1 $config_file)

# build the website
# assume this is run where
../gradlew clean build -x test

# clone the github-pages branch
readonly work_dir=$(mktemp -d)
readonly repo_dir="$work_dir/repo"
git clone -b github-pages git@github.com:cberes/$repo_name.git $repo_dir

# copy from master to github-pages branch
rm -fr $repo_dir/css $repo_dir/fonts $repo_dir/js $repo_dir/img
cp -r dist/* $repo_dir
cd $repo_dir
git add -A
git commit -m "update site"
git push
